<a href="https://colab.research.google.com/github/Saeed-upm/Numerical-Analysis/blob/main/Numerical_Analysis_4_Linear_Algebra_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
A = np.array([[1,2],[3,4],[5,6]])

In [ ]:
len(A)

3

In [ ]:
A = np.random.randn(5,5)
B = np.random.randn(5,2)
C = np.dot(A,B)
D = np.dot(B.T,A.T)
print(C.T-D)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
x = np.array([[2],[6],[3],[4]])

In [ ]:
xid = np.eye(x.shape[0]).dot(x)
xid

array([[2.],
       [6.],
       [3.],
       [4.]])

In [ ]:
r=x.shape

In [ ]:
print(r)

(3, 1)


In [ ]:
x.shape[1]

1

In [ ]:
A = np.random.randn(3,3)
A_inv = np.linalg.inv(A)
A_bis = A_inv.dot(A)
A_bis

array([[ 1.00000000e+00,  5.89577139e-18,  3.65982506e-16],
       [-1.10091431e-16,  1.00000000e+00, -2.38999966e-16],
       [ 1.71227531e-17, -2.92576426e-18,  1.00000000e+00]])